apiVersion: v1
kind: Secret
metadata:
  labels:
    app: grafana
  name: grafana-creds
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: codam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          envFrom:
          - secretRef:
              name: grafana-creds
          - secretRef:
              name: influxdb-creds
          image: rlucas-grafana:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources/influxdb-datasource.yml
            name: grafana-config
            readOnly: true
            subPath: influxdb-datasource.yml
          - mountPath: /etc/grafana/provisioning/datasources/grafana-dashboard-provider.yml
            name: grafana-config
            readOnly: true
            subPath: grafana-dashboard-provider.yml  ## subPath prevents overwriting other files in dir
      volumes:
        - configMap:
            name: grafana-config
          name: grafana-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - port: 3000
    name: grafana
