# Setup the load balancer
apiVersion: v1
kind: Service
metadata:
  name: rlucas-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: root
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  - port: 22
    name: ssh
  - port: 2000
    targetPort: 8443
    name: dash
  - port: 3000
    name: grafana
---
