apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlucas-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: rlucas-nginx
          image: rlucas-nginx:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 22
            - containerPort: 80
            - containerPort: 443

