apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      serviceAccountName: ip-grabber
      containers:
        - name: phpmyadmin
          envFrom:
          - secretRef:
              name: mysql-creds
          image: rlucas-phpmyadmin:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: phpmyadmin
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      name: http
