apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: telegraf
  name: telegraf-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: telegraf-influxdb-viewer
  labels:
    rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
rules:
  # Allow telegraf to get metrics from the metrics server
- apiGroups: ["", "metrics.k8s.io"]
  resources: ["persistentvolumes","nodes", "pods", "endpoints"]
  verbs: ["get","list","watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: telegraf-cr
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegraf-cr
subjects:
- kind: ServiceAccount
  name: telegraf-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf-sa
      containers:
        - name: telegraf
          image: rlucas-telegraf:1.0
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: influxdb-creds

# Scrap
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: telegraf-role
#   labels:
#     app: telegraf
#     rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
# rules:
# - apiGroups: ["apps", "", "metrics.k8s.io"]
#   resources: ["deployments", "pods", "services", "persistentvolumes", "nodes", "endpoints", "statefulsets"]
#   verbs: ["get", "list", "watch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   labels:
#     app: telegraf
#   name: telegraf-rolebinding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: telegraf-role
# subjects:
#   - kind: ServiceAccount
#     name: telegraf-serv-acc
#     namespace: default
#     apiGroup: ""
