apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: telegraf
  name: telegraf-serv-acc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegraf-role
  labels:
    app: telegraf
rules:
- apiGroups: ["apps", "", "metrics.k8s.io"]
  resources: ["deployments", "pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: telegraf
  name: telegraf-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegraf-role
subjects:
  - kind: ServiceAccount
    name: telegraf-serv-acc
    namespace: default
    apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlucas-telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf-serv-acc
      containers:
        - name: rlucas-telegraf
          image: rlucas-telegraf:1.0
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: influxdb-creds
